<a href="https://colab.research.google.com/github/rickylukman/Pemrosesan-Bahasa-Alami/blob/main/Klasifikasi_NLP_Pekan10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
# Upload File yang dibutuhkan, CSV dan Stopword
data_to_load = files.upload()

Saving dataset_sms_spam_v1.csv to dataset_sms_spam_v1.csv


In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
df = pd.read_csv("dataset_sms_spam_v1.csv")
df.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['Teks'], df['label'], test_size=0.2, shuffle=True)

In [ ]:
# Pembentukan tf-idf untuk pembobotan
vectorizer = TfidfVectorizer()
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [ ]:
%%time
modelknn = KNeighborsClassifier(n_neighbors=5, weights='distance')
modelknn.fit(x_train,y_train)

CPU times: user 1.99 ms, sys: 15 µs, total: 2.01 ms
Wall time: 1.9 ms


In [ ]:
y_pred = modelknn.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0,
       2, 1, 2, 0, 0, 2, 1, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1,
       2, 1, 0, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 0,
       2, 1, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 2, 0, 2, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 0, 0,
       2, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2,
       0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2,
       2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 1, 1, 2, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 1, 1, 0, 0, 2, 1, 0, 2,
       0, 2, 0, 2, 0, 1, 2, 0, 2])

In [ ]:
modelknn.predict_proba(x_test)

array([[1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.81252532, 0.18747468, 0.        ],
       [0.80980808, 0.19019192, 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.19916087, 0.80083913, 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.66572106, 0.33427894],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.15406063, 0.84593937],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[106   3   6]
 [  7  55   1]
 [  1   1  49]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.92      0.93       115
           1       0.93      0.87      0.90        63
           2       0.88      0.96      0.92        51

    accuracy                           0.92       229
   macro avg       0.91      0.92      0.91       229
weighted avg       0.92      0.92      0.92       229



In [ ]:
result_class = pd.DataFrame({'Actual Result':y_test, 'Predicted Result':y_pred})
result_class

Actual Result  Predicted Result
1017              0                 0
606               0                 0
497               1                 1
411               1                 1
548               1                 1
...             ...               ...
580               0                 0
324               1                 1
886               0                 2
1103              0                 0
31                2                 2

[229 rows x 2 columns]

## Cek Aktual dan Prediksi yang berbeda

In [ ]:
arr_actual = result_class["Actual Result"].to_numpy()
arr_predict = result_class["Predicted Result"].to_numpy()

In [ ]:
arr_diff = []
for i in range(len(arr_actual)):
  if arr_actual[i] != arr_predict[i]:
    arr_diff.append(i)

In [ ]:
lst = []
for i in range(len(arr_diff)):
  teks = df["Teks"].iloc[arr_diff[i]]
  actual_label = df["label"].iloc[arr_diff[i]]
  pred_label = y_pred[arr_diff[i]]
  lst.append([teks, actual_label, pred_label])
df_wrong = pd.DataFrame(lst, columns=['Teks', 'Actual', 'Predict'])

In [ ]:
df_wrong

Teks  Actual  Predict
0   Ambil bonus harianmu di *600# (Bebas Pulsa). D...       2        0
1   AYO download AXISnet dari PLAY/Apple Store dan...       2        2
2   Beli 1 Gratis 1 untuk Lychee Tea atau Latte Fl...       2        2
3   Beli 6 Gratis 6 Donut dari DUNKIN DONUTS BORMA...       2        2
4   Bisa Internetan 1,5GB CUMA dengan 20rb, paket ...       2        0
5   BONUS Rp. 5,000 untuk kamu! Cukup kirim SMS 2X...       2        0
6   Domino's PAN PIZZA!Rotinya lebih tebal dgn kej...       2        0
7   GRATIS 10GB! Bagi yg blm mengganti kartu SIM m...       2        1
8   JANGAN LUPA kirim 50 SMS sd 16 Juni 2013 utk m...       2        0
9   Jangan sampai kalah Bro, games mu bisa terbant...       2        1
10  Kartu 4G-LTE Anda telah aktif Dapatkan kuota t...       2        2
11  Kesempatan LANGKA! Cuma buat kamu saja loh, Da...       2        1
12  Mau cepat dan ga mau ribet cek pulsa & sisa ku...       2        2
13  Pakai XL tdk perlu repot setting bisa langsung...       2        0
14  Pembelian Dave's Single Burger Gratis Small Fr...       2        0
15  quota 1,5 GB harga hanya mulai 32,5 ribu, beli...       2        2
16  Selamat Anda mendapatkan voucher Zalora Rp100r...       2        1
17  Selamat Paket BBM Gratis Anda telah diaktifkan...       2        0
18  Tri berBAGI bonus PULSA di bulan pernuh berkah...       2        2